Data

In [ ]:
import pandas as pd

df_generators = pd.read_csv("data/powerplants.csv")

nodes = ["NO1", "NO2", "NO3", "NO4", "NO5"] #We define our problem over the 5 electrical zones in Norway

#Data that displays which generator types exist in each node
generators_of_node = pd.read_excel("Data/Sets.xlsx", sheet_name = "GeneratorsOfNode", skiprows=2)

#Initial capacity for each node and generator type combination
gen_capacities = pd.read_excel("Data/Generator.xlsx", sheet_name = "RefInitialCap", skiprows = 2)

#Initial capacity of each transmission line
trans_capacities = pd.read_excel("Data/Transmission.xlsx", sheet_name = "InitialCapacity", skiprows = 2)

#Investment cost for generators --> Does not include costs for maintaining installed capacity
inv_cost_gen = pd.read_excel("Data/Generator.xlsx", sheet_name = "CapitalCosts", skiprows = 2)

#Investment cost for transmission lines
trans_capacities = pd.read_excel("Data/Transmission.xlsx", sheet_name = "TypeCapitalCost", skiprows = 2)

#Variable cost for generators??
var_cost_gen = pd.read_excel("Data/Generator.xlsx", sheet_name = "VariableOMCost", skiprows = 2)
fuel_cost_gen = pd.read_excel("Data/Generator.xlsx", sheet_name = "FuelCost", skiprows = 2)

#Value of lost load??
val_ll = pd.read_excel("Data/Node.xlsx", sheet_name = "NodeLostLoadCost", skiprows = 2)

#Efficiency of directional flow a
dir_line_eff = pd.read_excel("Data/Transmission.xlsx", sheet_name = "LineEfficiency", skiprows = 2)


#----------------Scenario data-------------------------------------------------

#Electrical demand for each node MÅ BEARBEIDES MER?? --> se Empire dokumentasjon
#electricload
demands = pd.read_excel("Data/Node.xlsx", sheet_name = "ElectricalAnnualDemand", skiprows=2)

#Maximum available capacity of installed capacity og generator type in any given hour
solar_avail_cap = pd.read_csv("Data/solar.csv")
hydroror_avail_cap = pd.read_csv("Data/hydroror.csv")
windonshore = pd.read_csv("Data/windonshore.csv")

#Hydrogen max annual production --> Node/HydroGenMaxAnnualProduction
hydr_max_annual = pd.read_excel("Data/Node.xlsx", sheet_name = "HydrogenMaxAnnualProduction", skiprows=2)

#Max installed capacity V --> Generator/MaxInstalledCapacity
max_inst_cap = pd.read_excel("Data/Generator.xlsx", sheet_name = "MaxInstalledCapacity", skiprows=2)







#generator_availability = pd.read_excel("Data/Node.xlsx", sheet_name = "ElectricalAnnualDemand", skiprows=2)

#Generators = pd.read_excel("data/Generator.xlsx")
#Nodes = pd.read_excel("data/Nodes.xlsx")
#Sets = pd.read_excel("data/Sets.xlsx")
#Transmission = pd.read_excel("data/Transmission.xlsx")

In [ ]:
#Remove everything not related to the 5 Norwegian nodes

In [49]:
#Ectract the generator types for the 5 nodes
generators = generators_of_node[
    generators_of_node["Node"].isin(nodes)
].copy()

#Sort by node
generators = generators.sort_values("Node")

pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)

display(generators)

    Node               Generator
143  NO1                 Gas CCS
391  NO1  Hydro run-of-the-river
377  NO1                Gas CCGT
399  NO1            Wind onshore
409  NO1                   Solar
372  NO1                Gas OCGT
414  NO1                 Bio CCS
386  NO1         Hydro regulated
446  NO1                   Waste
548  NO1                 Nuclear
254  NO1                     Bio
387  NO2         Hydro regulated
447  NO2                   Waste
499  NO2  Wind offshore floating
404  NO2  Wind offshore grounded
392  NO2  Hydro run-of-the-river
549  NO2                 Nuclear
415  NO2                 Bio CCS
410  NO2                   Solar
400  NO2            Wind onshore
373  NO2                Gas OCGT
144  NO2                 Gas CCS
378  NO2                Gas CCGT
255  NO2                     Bio
411  NO3                   Solar
416  NO3                 Bio CCS
405  NO3  Wind offshore grounded
374  NO3                Gas OCGT
448  NO3                   Waste
401  NO3            Wind onshore
256  NO3                     Bio
500  NO3  Wind offshore floating
393  NO3  Hydro run-of-the-river
550  NO3                 Nuclear
388  NO3         Hydro regulated
379  NO3                Gas CCGT
368  NO3                 Gas CCS
449  NO4                   Waste
501  NO4  Wind offshore floating
257  NO4                     Bio
417  NO4                 Bio CCS
369  NO4                 Gas CCS
380  NO4                Gas CCGT
551  NO4                 Nuclear
389  NO4         Hydro regulated
406  NO4  Wind offshore grounded
394  NO4  Hydro run-of-the-river
402  NO4            Wind onshore
412  NO4                   Solar
375  NO4                Gas OCGT
390  NO5         Hydro regulated
376  NO5                Gas OCGT
502  NO5  Wind offshore floating
395  NO5  Hydro run-of-the-river
413  NO5                   Solar
403  NO5            Wind onshore
258  NO5                     Bio
418  NO5                 Bio CCS
407  NO5  Wind offshore grounded
370  NO5                 Gas CCS
381  NO5                Gas CCGT
450  NO5                   Waste
552  NO5                 Nuclear

In [46]:
presence = (
    generators
    .assign(Exists=generators["InitialCapacity"] > 0)
    .pivot_table(
        index="GeneratorTechnology",
        columns="Node",
        values="Exists",
        aggfunc="max",
        fill_value=False
    )
)

presence = presence.reindex(
    columns=["NO1", "NO2", "NO3", "NO4", "NO5"]
)

display(presence)

KeyError: 'InitialCapacity'

Data imports

In [16]:
df_generators_norway = df_generators[df_generators["Country"] == "Norway"]
df_generators_norway.head()

,id,Name,Fueltype,Technology,Set,Country,Capacity,Efficiency,DateIn,DateRetrofit,DateOut,lat,lon,Duration,Volume_Mm3,DamHeight_m,StorageCapacity_MWh,EIC,projectID
157,157,Saurdal,Hydro,Reservoir,Store,Norway,640.0,NaN,1970.0,1985.0,NaN,59.4791,6.6924,4988.925000,3112.0,437.0,3192912.0,{nan},"{'GEM': {'G100000602998'}, 'JRC': {'JRC-N362'}..."
158,158,Duge,Hydro,Reservoir,Store,Norway,200.0,NaN,1970.0,1979.0,NaN,59.1289,6.8922,3885.000000,1400.0,220.0,777000.0,{nan},"{'GEM': {'G100000602935'}, 'JRC': {'JRC-N64'},..."
159,159,Aurland,Hydro,Reservoir,Store,Norway,290.0,NaN,1970.0,1983.0,NaN,60.8009,7.5666,1556.385185,448.0,400.0,420224.0,{nan},"{'GEM': {'G100000602924'}, 'JRC': {'JRC-N13'},..."
163,163,Svartisen,Hydro,Reservoir,Store,Norway,720.0,NaN,1970.0,2011.0,NaN,66.7295,13.9144,8116.390000,3506.0,543.0,4869834.0,{nan},"{'GEM': {'G100000603015'}, 'JRC': {'JRC-N542'}..."
164,164,Straumsmo,Hydro,Reservoir,Store,Norway,130.0,NaN,1965.0,1966.0,NaN,68.7408,18.6433,14.686154,3.7,229.0,1909.2,{nan},"{'GEM': {'G100000603010'}, 'JRC': {'JRC-N404'}..."